package iconnet

import (
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"testing"
)

// loadNpy reads the raw data (skip header) of a float32 npy written by
// np.save. Returns the flat float64 array.
func loadNpy(path string) ([]float64, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	// magic \x93NUMPY then a dict then \n then aligned data
	if len(b) < 10 || string(b[0:6]) != "\x93NUMPY" {
		return nil, fmt.Errorf("bad npy %s", path)
	}
	i := 6
	major, minor := b[i], b[i+1]
	i += 2
	var hlen int
	switch major {
	case 1:
		hlen = int(binary.LittleEndian.Uint16(b[i:]))
		i += 2
	case 2:
		hlen = int(binary.LittleEndian.Uint32(b[i:]))
		i += 4
	default:
		return nil, fmt.Errorf("unsupported npy version %d.%d", major, minor)
	}
	_ = minor
	data := b[i+hlen:]
	n := len(data) / 4
	out := make([]float64, n)
	for j := 0; j < n; j++ {
		out[j] = float64(math.Float32frombits(binary.LittleEndian.Uint32(data[j*4:])))
	}
	return out, nil
}

// TestLoadWeights verifies the exported weights file loads and a forward pass
// runs (smoke).
func TestLoadWeights(t *testing.T) {
	net, err := LoadFile(filepath.Join("weights.bin"))
	if err != nil {
		t.Fatal(err)
	}
	if len(net.Ch) != 4 {
		t.Fatalf("want 4 blocks, got %d", len(net.Ch))
	}
	if net.EmbDim != 64 {
		t.Fatalf("want emb 64, got %d", net.EmbDim)
	}
	x := make([]float64, 4*64*64)
	for i := range x {
		x[i] = float64(i%255) / 255.0
	}
	e := net.Embed(x)
	if len(e) != 64 {
		t.Fatalf("emb len %d", len(e))
	}
	if Norm(e) < 0.999 || Norm(e) > 1.001 {
		t.Fatalf("embedding not normalized: %f", Norm(e))
	}
}

// TestAlignment compares Go embeddings against Python reference embeddings and
// verifies query->ref retrieval matches the Python pipeline.
//
// Reference files are generated by the pynet alignment script (see
// pynet/align_go.py) into dir; this test is skipped when they are absent.
func TestAlignment(t *testing.T) {
	refJSON := filepath.Join("..", "test_align", "refs.json")
	if _, err := os.Stat(refJSON); err != nil {
		t.Skipf("reference data not present (run align_go.py first): %v", err)
	}
	net, err := LoadFile(filepath.Join("weights.bin"))
	if err != nil {
		t.Fatal(err)
	}
	raw, _ := os.ReadFile(refJSON)
	var refs map[string]struct {
		Emb string `json:"emb"`
		Src string `json:"src"`
	}
	if err := json.Unmarshal(raw, &refs); err != nil {
		t.Fatal(err)
	}
	maxDiff := 0.0
	for k, r := range refs {
		sp, err := loadNpy(filepath.Join("..", "test_align", k+".npy"))
		if err != nil {
			t.Fatal(err)
		}
		n := int(math.Sqrt(float64(len(sp) / 4)))
		sp = sp[:n*n*4]
		// npy is HWC RGBA; convert to NCHW tensor
		tens := hwcToNCHW(sp, n)
		e := net.Embed(tens)
		want := make([]float64, 64)
		rb, _ := base64.StdEncoding.DecodeString(r.Emb)
		for j := 0; j < 64; j++ {
			want[j] = float64(math.Float32frombits(binary.LittleEndian.Uint32(rb[j*4:])))
		}
		d := 0.0
		for j := 0; j < 64; j++ {
			diff := math.Abs(e[j] - want[j])
			if diff > d {
				d = diff
			}
		}
		if d > maxDiff {
			maxDiff = d
		}
		if d > 1e-4 {
			t.Errorf("%s max abs diff = %g (cos=%.6f)", k, d, Cosine(e, want))
		}
	}
	t.Logf("max abs element diff across %d sprites: %g", len(refs), maxDiff)
}

// hwcToNCHW converts a flat HWC RGBA float array to the NCHW tensor
// (values in [0,255] scaled to [0,1]).
func hwcToNCHW(hwc []float64, n int) []float64 {
	out := make([]float64, 4*n*n)
	for y := 0; y < n; y++ {
		for x := 0; x < n; x++ {
			i := (y*n + x) * 4
			for c := 0; c < 4; c++ {
				out[c*n*n+y*n+x] = hwc[i+c] / 255.0
			}
		}
	}
	return out
}
